- name: Install Cron Job (Ansible Pull)
  cron:
    user: ansible
    name: "Ansible Provisioning" 
    minute: "*/10"
    job: "/home/geo/.local/bin/ansible-pull -o -U https://github.com/Geo-GmZ/ansible-pull.git > /home/geo/Ansible/pull.log"

