- name: Install Cron Job (Ansible Pull)
  cron:
    user: ansible
    name: "Ansible Provisioning" 
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/Geo-GmZ/workstation-setup-playbook.git > /home/ansible/pull.log"

