  - name: Allow Connections from Loopback.
    iptables: 
      chain: INPUT
      in_interface: lo
      jump: ACCEPT
      rule_num: 1
    become: yes
  
  - name: Allow Stablished, Related connections.
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
      rule_num: 2
    become: yes
    
  - name: Set INPUT policy to DROP all.
    iptables: 
      chain: INPUT
      policy: DROP
    become: yes
    
    
